package com.rui.pvpgo.live

import com.rui.pvpgo.domain.*

private var count=0
private fun checkThat(result:Boolean,label:String){check(result){label};count++}
private val owned = listOf(OwnedPokemon("a","clodsire","Clodsire"),
    OwnedPokemon("b","feraligatr","Feraligatr"),OwnedPokemon("c","mandibuzz","Mandibuzz"),
    OwnedPokemon("d","lanturn","Lanturn"))
private fun team(id:String="t", primary:Boolean=false,updated:Long=1, members:List<TeamMember> = listOf(
    TeamMember("a",TeamRole.LEAD),TeamMember("b",TeamRole.SAFE_SWITCH),TeamMember("c",TeamRole.CLOSER))) =
    SavedTeam(id,"Equipa $id",League.GREAT,members,primary,updated)
fun main(){
    val valid=CompanionManualTeamPolicy.options(listOf(team()),owned)
    checkThat(valid.size==1,"one option")
    checkThat(valid.single().selectable,"ready team")
    checkThat(valid.single().disabledReason==null,"no warning")
    checkThat(valid.single().members.size==3,"three members")
    checkThat(valid.single().members.map{it.role}==TeamRole.entries,"canonical roles")
    checkThat(valid.single().members.map{it.ownedPokemonId}==listOf("a","b","c"),"canonical IDs")
    checkThat(valid.single().members.map{it.displayName}==listOf("Clodsire","Feraligatr","Mandibuzz"),"real nicknames")
    val old=CompanionTeamSelection().chooseTeam("t",valid)
    checkThat(old.selectedTeamId=="t","selected id")
    checkThat(old.activeOwnedPokemonId==null,"no auto lead")
    val active=old.chooseActive("b",valid)
    checkThat(active.activeOwnedPokemonId=="b","manual active")
    checkThat(active.chooseActive("missing",valid).activeOwnedPokemonId==null,"unknown active rejected")
    checkThat(active.chooseTeam(null,valid).selectedTeamId==null,"clear selection")
    checkThat(active.chooseTeam(null,valid).activeOwnedPokemonId==null,"clear active")
    checkThat(active.chooseTeam("unknown",valid).selectedTeamId==null,"unknown team rejected")
    checkThat(active.forSession("s1").activeOwnedPokemonId==null,"new session resets active")
    checkThat(active.forSession("s1").selectedTeamId=="t","team stays user entered")
    val s1=active.forSession("s1").chooseActive("c",valid)
    checkThat(s1.forSession("s1")==s1,"same session preserved")
    checkThat(s1.forSession("s2").activeOwnedPokemonId==null,"different session clears active")
    checkThat(s1.forSession(null).activeOwnedPokemonId==null,"stop session clears active")
    checkThat(s1.validated(valid)==s1,"valid room snapshot preserved")
    val removed=CompanionManualTeamPolicy.options(listOf(team()),owned.filter{it.id!="b"})
    checkThat(!removed.single().selectable,"deleted pokemon invalidates")
    checkThat(removed.single().disabledReason?.contains("removido")==true,"removed reason")
    checkThat(s1.validated(removed).selectedTeamId==null,"invalid room clears team")
    checkThat(s1.validated(removed).activeOwnedPokemonId==null,"invalid room clears active")
    val wrongRole=team(members=listOf(TeamMember("a",TeamRole.LEAD),TeamMember("b",TeamRole.LEAD),TeamMember("c",TeamRole.CLOSER)))
    checkThat(!CompanionManualTeamPolicy.options(listOf(wrongRole),owned).single().selectable,"duplicate role refused")
    val dup=team(members=listOf(TeamMember("a",TeamRole.LEAD),TeamMember("a",TeamRole.SAFE_SWITCH),TeamMember("c",TeamRole.CLOSER)))
    checkThat(!CompanionManualTeamPolicy.options(listOf(dup),owned).single().selectable,"duplicate specimen refused")
    val empty=CompanionManualTeamPolicy.options(emptyList(),owned)
    checkThat(empty.isEmpty(),"empty collection no fake")
    checkThat(CompanionTeamSelection().chooseTeam("t",empty).selectedTeamId==null,"empty cannot select")
    val missing=CompanionManualTeamPolicy.options(listOf(team()),emptyList())
    checkThat(missing.single().members.isEmpty(),"empty owned no members")
    checkThat(!missing.single().selectable,"empty owned disabled")
    val sorted=CompanionManualTeamPolicy.options(listOf(team("b",updated=20),team("c",true,5),team("a",updated=3)),owned)
    checkThat(sorted.map{it.id}==listOf("c","b","a"),"primary and recent order")
    val unnamed=CompanionManualTeamPolicy.options(listOf(team()),owned.map{if(it.id=="a")it.copy(nickname="  ")else it})
    checkThat(unnamed.single().members[0].displayName=="clodsire","species fallback")
    checkThat(active.validated(CompanionManualTeamPolicy.options(listOf(team(id="different")),owned)).selectedTeamId==null,"renamed id invalidates")
    checkThat(CompanionTeamSelection(sessionId="s",selectedTeamId=null).chooseActive("a",valid).activeOwnedPokemonId==null,"no team no active")
    checkThat(CompanionTeamSelection(selectedTeamId="t",activeOwnedPokemonId="missing").validated(valid).activeOwnedPokemonId==null,"stale active cleared")
    checkThat(CompanionTeamSelection().chooseTeam("t",removed).selectedTeamId==null,"disabled team cannot select")
    checkThat(CompanionManualTeamPolicy.options(listOf(team()),owned).single().leagueName=="GREAT","real league")
    val opponent=CompanionManualOpponent().enter("  Mr.   Mime   ")
    checkThat(opponent.enteredName=="Mr. Mime","manual name normalization")
    checkThat(opponent.enter("   ").enteredName==null,"empty opponent is unknown")
    checkThat(opponent.enter("a".repeat(80)).enteredName?.length==48,"manual name bounded")
    checkThat(opponent.forSession("one").enteredName==null,"fresh session clears rival")
    checkThat(opponent.forSession("one").enter("Lanturn").forSession("one").enteredName=="Lanturn","same session retains manual name")
    checkThat(opponent.forSession("one").enter("Lanturn").forSession("two").enteredName==null,"session change clears rival")
    checkThat(opponent.clear().enteredName==null,"clear rival")
    checkThat(CompanionManualOpponent().enteredName==null,"unknown by default")
    println("COMPANION_V149_MANUAL_TEAM_PASS checks=$count")
}
